create extension if not exists pgcrypto;

create schema if not exists private;
revoke all on schema private from public;

create table if not exists public.profiles (
  id uuid primary key references auth.users(id) on delete cascade,
  username text not null unique,
  email text not null unique,
  is_admin boolean not null default false,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.user_settings (
  id bigint generated by default as identity primary key,
  user_id uuid not null references public.profiles(id) on delete cascade,
  setting_key text not null,
  setting_value text not null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique(user_id, setting_key)
);

create table if not exists public.user_words (
  id bigint generated by default as identity primary key,
  user_id uuid not null references public.profiles(id) on delete cascade,
  english text not null,
  farsi text not null,
  ticks integer not null default 0 check (ticks between 0 and 8),
  last_reviewed timestamptz,
  date_added timestamptz not null default now(),
  learned boolean not null default false,
  in_re_review boolean not null default false,
  review_history jsonb not null default '[]'::jsonb,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique(user_id, english)
);

create table if not exists public.user_stats (
  id bigint generated by default as identity primary key,
  user_id uuid not null references public.profiles(id) on delete cascade,
  stat_date date not null,
  total_reviews integer not null default 0,
  correct_answers integer not null default 0,
  wrong_answers integer not null default 0,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique(user_id, stat_date)
);

create table if not exists public.total_reviews (
  id bigint generated by default as identity primary key,
  user_id uuid not null references public.profiles(id) on delete cascade,
  word_id bigint references public.user_words(id) on delete set null,
  reviewed_at timestamptz not null default now(),
  is_correct boolean not null default false,
  tick_after integer not null default 0,
  response jsonb
);

create table if not exists public.collections (
  id bigint generated by default as identity primary key,
  name text not null,
  description text,
  type text not null default 'dictionary' check (type in ('dictionary','story','pdf','video')),
  cover_image text,
  cover_color text not null default '#6366f1',
  video_url text,
  pdf_url text,
  total_words integer not null default 0,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.collection_words (
  id bigint generated by default as identity primary key,
  collection_id bigint not null references public.collections(id) on delete cascade,
  english text not null,
  farsi text not null,
  example text,
  unit integer not null default 1,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique(collection_id, english, unit)
);

create table if not exists public.collection_stories (
  id bigint generated by default as identity primary key,
  collection_id bigint not null references public.collections(id) on delete cascade,
  chapter_number integer not null default 1,
  chapter_title text not null default 'فصل 1',
  content text not null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique(collection_id, chapter_number)
);

create index if not exists idx_user_words_user on public.user_words(user_id,id);
create index if not exists idx_user_words_learning on public.user_words(user_id,learned,in_re_review);
create index if not exists idx_user_stats_user_date on public.user_stats(user_id,stat_date desc);
create index if not exists idx_total_reviews_user_date on public.total_reviews(user_id,reviewed_at desc);
create index if not exists idx_collection_words_collection_unit on public.collection_words(collection_id,unit,id);
create index if not exists idx_collection_stories_collection_chapter on public.collection_stories(collection_id,chapter_number);

create or replace function public.handle_new_user()
returns trigger language plpgsql security definer set search_path=public as $$
declare uname text;
begin
  uname:=coalesce(nullif(new.raw_user_meta_data->>'username',''),split_part(new.email,'@',1));
  insert into public.profiles(id,username,email) values(new.id,uname,new.email)
  on conflict(id) do update set email=excluded.email;
  insert into public.user_settings(user_id,setting_key,setting_value)
  values(new.id,'study_start_date',current_date::text),(new.id,'daily_limit','20')
  on conflict(user_id,setting_key) do nothing;
  return new;
end; $$;

drop trigger if exists on_auth_user_created on auth.users;
create trigger on_auth_user_created after insert on auth.users
for each row execute function public.handle_new_user();

create or replace function public.touch_updated_at()
returns trigger language plpgsql set search_path=public as $$
begin new.updated_at=now(); return new; end; $$;

do $$ declare t text; begin
  foreach t in array array['profiles','user_settings','user_words','user_stats','collections','collection_words','collection_stories'] loop
    execute format('drop trigger if exists touch_%I on public.%I',t,t);
    execute format('create trigger touch_%I before update on public.%I for each row execute function public.touch_updated_at()',t,t);
  end loop;
end $$;

create or replace function private.is_admin(uid uuid default auth.uid())
returns boolean language sql stable security definer set search_path=public as $$
  select exists(select 1 from public.profiles where id=uid and is_admin=true);
$$;

grant usage on schema private to authenticated;
grant execute on function private.is_admin(uuid) to authenticated;

create or replace function public.review_word(p_word_id bigint,p_correct boolean)
returns jsonb language plpgsql security invoker set search_path=public as $$
declare
  uid uuid:=auth.uid();
  w public.user_words%rowtype;
  hist jsonb;
  reds integer:=0;
  new_ticks integer;
  learned_now boolean;
begin
  if uid is null then raise exception 'not authenticated'; end if;
  select * into w from public.user_words where id=p_word_id and user_id=uid for update;
  if not found then raise exception 'word not found'; end if;
  if w.last_reviewed is not null and
     (w.last_reviewed at time zone 'Asia/Tehran')::date=(now() at time zone 'Asia/Tehran')::date
  then raise exception 'already reviewed today'; end if;

  hist:=coalesce(w.review_history,'[]'::jsonb);

  if p_correct then
    new_ticks:=least(8,w.ticks+1);
    hist:=hist||jsonb_build_array(jsonb_build_object(
      'date',to_char(now() at time zone 'Asia/Tehran','YYYY-MM-DD HH24:MI:SS'),
      'type','green','tick_number',new_ticks));
    learned_now:=new_ticks>=6;
    update public.user_words
    set ticks=new_ticks,last_reviewed=now(),learned=learned_now,in_re_review=false,review_history=hist
    where id=w.id;
  else
    hist:=hist||jsonb_build_array(jsonb_build_object(
      'date',to_char(now() at time zone 'Asia/Tehran','YYYY-MM-DD HH24:MI:SS'),
      'type','red','previous_ticks',w.ticks));
    select count(*) into reds from jsonb_array_elements(hist) x where x->>'type'='red';
    if reds>=3 then
      update public.user_words
      set ticks=0,last_reviewed=now(),learned=false,in_re_review=true,review_history='[]'::jsonb
      where id=w.id;
      new_ticks:=0; learned_now:=false;
    else
      update public.user_words
      set last_reviewed=now(),in_re_review=false,review_history=hist
      where id=w.id;
      new_ticks:=w.ticks; learned_now:=w.learned;
    end if;
  end if;

  insert into public.total_reviews(user_id,word_id,is_correct,tick_after,response)
  values(uid,w.id,p_correct,new_ticks,jsonb_build_object('red_count',reds));

  insert into public.user_stats(user_id,stat_date,total_reviews,correct_answers,wrong_answers)
  values(uid,(now() at time zone 'Asia/Tehran')::date,1,
         case when p_correct then 1 else 0 end,
         case when p_correct then 0 else 1 end)
  on conflict(user_id,stat_date) do update set
    total_reviews=public.user_stats.total_reviews+1,
    correct_answers=public.user_stats.correct_answers+excluded.correct_answers,
    wrong_answers=public.user_stats.wrong_answers+excluded.wrong_answers,
    updated_at=now();

  return jsonb_build_object(
    'success',true,'newTicks',new_ticks,'learned',learned_now,
    'inReReview',(select in_re_review from public.user_words where id=w.id),
    'totalReds',reds);
end; $$;

grant execute on function public.review_word(bigint,boolean) to authenticated;

alter table public.profiles enable row level security;
alter table public.user_settings enable row level security;
alter table public.user_words enable row level security;
alter table public.user_stats enable row level security;
alter table public.total_reviews enable row level security;
alter table public.collections enable row level security;
alter table public.collection_words enable row level security;
alter table public.collection_stories enable row level security;

create policy profiles_select_self_or_admin on public.profiles
for select to authenticated
using ((select auth.uid())=id or private.is_admin((select auth.uid())));

create policy profiles_update_self on public.profiles
for update to authenticated
using ((select auth.uid())=id)
with check ((select auth.uid())=id);

create policy settings_self on public.user_settings
for all to authenticated
using ((select auth.uid())=user_id)
with check ((select auth.uid())=user_id);

create policy words_self on public.user_words
for all to authenticated
using ((select auth.uid())=user_id)
with check ((select auth.uid())=user_id);

create policy stats_self on public.user_stats
for all to authenticated
using ((select auth.uid())=user_id)
with check ((select auth.uid())=user_id);

create policy reviews_self on public.total_reviews
for all to authenticated
using ((select auth.uid())=user_id)
with check ((select auth.uid())=user_id);

create policy collections_public_read on public.collections
for select to anon,authenticated using (true);

create policy collection_words_public_read on public.collection_words
for select to anon,authenticated using (true);

create policy collection_stories_public_read on public.collection_stories
for select to anon,authenticated using (true);

create policy collections_admin_write on public.collections
for all to authenticated
using (private.is_admin((select auth.uid())))
with check (private.is_admin((select auth.uid())));

create policy collection_words_admin_write on public.collection_words
for all to authenticated
using (private.is_admin((select auth.uid())))
with check (private.is_admin((select auth.uid())));

create policy collection_stories_admin_write on public.collection_stories
for all to authenticated
using (private.is_admin((select auth.uid())))
with check (private.is_admin((select auth.uid())));

revoke all on public.profiles,public.user_settings,public.user_words,public.user_stats,
  public.total_reviews,public.collections,public.collection_words,public.collection_stories from anon;

grant select on public.collections,public.collection_words,public.collection_stories to anon,authenticated;
grant select,insert,update,delete on public.user_settings,public.user_words,public.user_stats,public.total_reviews to authenticated;
grant select,update on public.profiles to authenticated;
grant insert,update,delete on public.collections,public.collection_words,public.collection_stories to authenticated;

revoke execute on function public.handle_new_user() from public,anon,authenticated;
revoke execute on function public.review_word(bigint,boolean) from public,anon;
